### ISSUE TITLE
CTAN upload does not include ins file

### ISSUE THREAD

**Issue by moewew** [patta42/lipsum#11]
As of today (2018-11-24) the version `lipsum` package on CTAN does not include the `.ins` file. https://ctan.org/tex-archive/macros/latex/contrib/lipsum only lists 

- `README.txt`
- `lipsum.dtx`
- `lipsum.pdf`

while the README additionally lists `lipsum.ins` amongst the distributed files (incidentally according to the README itself, the README should be called `README.1st` and not `README.txt`). The `.dtx` also does not seem to contain a self-extracting `.ins` so that the package as downloaded from CTAN can not be installed properly.

This is causing issues for MikTeX since the `.sty` can't be produced, see https://github.com/MiKTeX/miktex-packaging/issues/67 and https://github.com/MiKTeX/miktex-packaging/issues/68.

As it turns out TeX live managed to get an `.ins` file (from somewhere else? - I assume GitHub and not CTAN) and correctly installs a `.sty` file:  https://tug.org/pipermail/tex-live-commits/2018-November/007831.html

**Comment by patta42** [comment]
I have uploaded a new zip file to CTAN containing the `.ins`-file. Should be available soon.

**Comment by moewew** [comment]
Thank you for the quick reply.
