### ISSUE TITLE
! LaTeX3 Error: File 'lipsum.ltd' not found.

### ISSUE THREAD

**Issue by dbitouze** [patta42/lipsum#14]
Hi,

after this morning TeX Live update and the new 2.2 version of `lipsum`, the following MCE:
```latex
\documentclass{article}
\usepackage{lipsum}
\begin{document}
\lipsum
\end{document}
```
fails to compile with the message:
>! LaTeX3 Error: File 'lipsum.ltd' not found.

Already reported [on TeX Live mailing list](https://tug.org/pipermail/tex-live/2019-January/043043.html) but not sure whether the culprit is the package itself or its integration in TL, hence the report here.

**Comment by patta42** [comment]
This seems to be a problem of TeXlive. It only ships `lipsum.sty`, which is not sufficient since version 2.2. The `lipsum.ins` file on CTAN contains the commands to generate the required additional files and the message produced by running it through latex says how to install it properly.

**Comment by dbitouze** [comment]
Indeed, it was just a problem from TeX Live side, fixed with its last update. Sorry for the noise here.
