### ISSUE TITLE
Feature request: provide text without enclosing in group braces

### ISSUE THREAD

**Issue by bersbersbers** [patta42/lipsum#18]
This may be related to #17, but I post it separately nonetheless.

This errors, likely because of a limitation in `soul`, but that one seems hard to resolve (otherwise it would have been solved already):

```
\documentclass{article}
\usepackage{soul,lipsum}
\begin{document}
    \hl{\lipsum}
\end{document}
```

> l.4 `\hl{\lipsum}`
> I came across hyphenatable material enclosed in group braces,
> which I can't handle. Either drop the braces or make the material
> unbreakable using an \mbox (\hbox). Note that a space
> also counts as possible hyphenation point. See page 4 of the manual.
> I'm leaving a black square so that you can see where I am right now.

I have also tried
```
\unpacklipsum\hl{\lipsumexp}
```
with the same result.

Could `lipsum` provide the text without "enclosing it in group braces"?

**Comment by patta42** [comment]
It will be too complicated to provide the dummy without groups and keeping the current interface. if you want to use lipsum with soul, use something like:

```
\documentclass{article}
\usepackage{soul, lipsum}
\unpacklipsum*
\begin{document}

\expandafter\hl\expandafter{\lipsumexp}
\end{document}

```

**Comment by bersbersbers** [comment]
Thanks!

**Comment by bersbersbers** [comment]
For the record, I am now using
```
\renewcommand{\lipsum}[1][]{\unpacklipsum[#1]\expandafter\hl\expandafter{\lipsumexp}}
```
and this seemed to be working fine. However, multiple paragraphs are joint in a weird way:

```
\documentclass{article}
\usepackage{soul, lipsum}
\unpacklipsum[1-2]
\begin{document}
\expandafter\hl\expandafter{\lipsumexp}
\end{document}
```

![image](https://user-images.githubusercontent.com/12128514/93716691-8df8f200-fb71-11ea-9516-5b238754d1c4.png)
