### ISSUE TITLE
Should \lipsum[1][1-3] drop the \par?

### ISSUE THREAD

**Issue by FrankMittelbach** [patta42/lipsum#2]
I think not. In my opinion it shoud get the same final terminator as \lipsum[1].

**Comment by patta42** [comment]
I was thinking about this, but the situation is slightly more complicated.

- Should `\lipsum[1][1000-1001]` (i.e., an empty sentence range) be just `\par` or nothing?
- Should `\lipsum[78-79][11-12]`, (i.e, a sentence range spanning two paragraphs) be <sentence11 from par78>`\par`<sentence1 from par78>`\par`?
- Should `\lipsum[78][11]` (i.e., selecting the last sentence from a paragraph) be <sentence>`\par \par`?

I have to think about this. Just inserting a \space was simply much easier.

**Comment by FrankMittelbach** [comment]
> I was thinking about this, but the situation is slightly more complicated.

agreed. One can of course document that using using the sentence arg 
means you just get a list of sentences no terminator, no meaning for * form.

Or

logic is it will always result in a single "paragraph" with a terminator 
based on setting of options and *

In the latter case (assuming no option on package level)
> 
>   * Should |\lipsum[1][1000-1001]| (i.e., an empty sentence range) be
>     just |\par| or nothing?

\par
>   * Should |\lipsum[78-79][11-12]|, (i.e, a sentence range spanning two
>     paragraphs) be |\par||\par|?

text from 78 \space  text from 79 \par

>   * Should |\lipsum[78][11]| (i.e., selecting the last sentence from a
>     paragraph) be |\par \par|?

text from 78 \par

why \par \par?

> I have to think about this. Just inserting a \space was simply much easier.

sure it is an option :-)

**Comment by patta42** [comment]
> why \par \par?

I had added "sentence from par 78" and similar, but in angle brackets, which is not displayed.

**Comment by patta42** [comment]
I have implemented a mechnism which allows to fine-tune much more than the `\par`s in between and at the end of the paragraps/sentences.

Default settings are:
- Sentences are separated by `\space`
- In par-mode, the selected sentences are terminated by `\par`, a single paragraph is generated
- In nopar-mode ,the selected sentences are terminated by `\space`, text can directly follow to end the paragraph.

(par-mode: no package option, `\lipsum` or `nopar` option and `\lipsum*`, nopar-mode vice-versa)

I guess, further discussion about the new system or its default settings should go in a new issue. 
 
9d069dfa4550d1d9c8ff441173e586717c428484
5240873b39404d6120ccd02be0da2fc238cfa121
