### ISSUE TITLE
not using regex?

### ISSUE THREAD

**Issue by FrankMittelbach** [patta42/lipsum#4]
While I agree that when scanning for a period, regex is a kind of obvious choice, but it is clearly very inefficient to first build very long peragraphs and then do an elaborate scanning loop on them (hence `\lipsum[1][1]` being much much faster than `\lipsum[1-50][1]`). Probably better to do the parsing dírectly here using coding like done for` \clist...`

**Comment by patta42** [comment]
980e777eaffd7124be3701724f5ea00013550f49
