### ISSUE TITLE
nopar, really?

### ISSUE THREAD

**Issue by FrankMittelbach** [patta42/lipsum#5]
> While this seems strange (and has been filed as a bug), this is the documented
> behaviour.

I can't see any purpose in having that, it is a bug imho and you should in my opinion make `nopar` behave like the new `space` option (which then isn't needed). What should be the use case for it? Even backward compatibility isn't an argument as far as I can see.

and the mix of both options and its behavior is an interesting mental exercise :-) but I don't see what good would that do.

If there is a space at the end a following manual `\par` will remove that anyway. so in all practical purposes they are equal, except that something like `\lipsum[1-2]` is not usable with `nopar`

**Comment by patta42** [comment]
it is not a bug (in my opinion), but a quite useless feature :-) And I agree that a space instead of `\relax` or `\prg_do_nothing:` is much more useful. I'll drop the option `space` and will change `nopar` accordingly.

**Comment by patta42** [comment]
2204d86b5af76a4cd3e16b046633a169ff0df73a
