### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by patta42** [patta42/lipsum#7]
Due to a lot of changes in the code in the past days, the docs have to be reviewed and updated.

**Comment by patta42** [comment]
1068b4188812ad17c33b1b0f3532e0b3eb107fc8

**Comment by tmelorc** [comment]
I think in version from November 8, 2018, Section 3.3, 2nd paragraph of the documentation, contains a typo. 

```
(the famous żLorem ipsum dolor sit amet, consectetuer
adipiscing elit.ń).
```

**Comment by patta42** [comment]
> I think in version from November 8, 2018, Section 3.3, 2nd paragraph of the documentation, contains a typo.

It was not a true typo (as you can see from the code), but the docs were typeset with the wrong engine (the build.lua file obviously uses pdflatex). Seconds ago, I have uploaded v2.1 to CTAN (with some changes in the default settings), and generated the pdf manually . It should be correct now.
